### ISSUE TITLE
It's possible to extract classes from hiccup keyword tag.

### ISSUE THREAD

**Issue by DogLooksGood** [jacekschae/shadow-cljs-tailwindcss#15]
Hi, good example for shadow/tailwind integration.

I think we can write class name in keyword tag with following configuration.
```
purge: {
    content: ["./src/**/*.cljs"],
    options: {
      defaultExtractor: content => content.match(/[^<>"'.`\s]*[^<>"'.`\s:]/g)
    }
  },
```

**Comment by jacekschae** [comment]
Thanks for taking the time to create the issue. Did you maybe had a chance to read the part about how we generate classes / which files we observe in the README (Live reload) or looked at `tailwindcss.config.js`. We are not really looking at `*.cljs` files, but rather at the output of shadow-cljs `*.js` at this point hiccup shorthand class names are already strings therefore custom extractor is not needed.

**Comment by jacekschae** [comment]
@DogLooksGood do you think we can close this one?

**Comment by DogLooksGood** [comment]
Let me give a try on this, I think the default extractor will not consider dot as a boundary. So with string like `"div.foo.bar"`, it will extract `["div.foo.bar"]`, not `["div", "foo", "bar"]`.
