### ISSUE TITLE
Repeated link tag?

### ISSUE THREAD

**Issue by aiba** [jacekschae/shadow-cljs-tailwindcss#188]
In `public/index.html` it looks like [line 7](https://github.com/jacekschae/shadow-cljs-tailwindcss/blob/47ef1feaca625e20031cf3913a6ee3ff4eb8c012/public/index.html#L7) is a repeat of line 5.  Is that necessary?

**Comment by jacekschae** [comment]
You are right it's a mistake. Thanks!
