### ISSUE TITLE
invoke cross-env with node_modules path

### ISSUE THREAD

**Issue by geraldodev** [jacekschae/shadow-cljs-tailwindcss#210]
Hi, 

Thank you for this project. I've used as a basis for changing my setup to use tailwind. I'm using ubuntu.

I had to add the path of node_modules in order to cross-env to be invoked successfully.
```
 "postcss:build": "node node_modules/cross-env/src/bin/cross-env.js TAILWIND_MODE=build postcss css/tailwind.css -o ./resources/public/css/app.css --verbose",
```

Maybe it's because you install cross-env as dependency instead of devDependencies which I think is more right.

**Comment by jacekschae** [comment]
Thanks for reporting this. 

Did you maybe tray with installing via devDependencies? Was the result different?

**Comment by geraldodev** [comment]
I gave up on using cross-env, I'm invoking two separate processes, one for shadow and one for tailwind. What I'm experiencing with tailwint is the slowness over time until the point of locking. I think its because of https://github.com/tailwindlabs/tailwindcss/issues/7449 . It took a morning working until the lock up happend. At  afternoon I didnt start the tailwind process , and keep using vim and shadow on the same project editing the same code, without lock up.
