### ISSUE TITLE
Improve developer experience on initial load

### ISSUE THREAD

**Issue by jacobemcken** [jacekschae/shadow-cljs-tailwindcss#295]
Initial load looks wonky because CSS isn't built correctly.

See #285 for a suggestion to fix it.

**Comment by jacekschae** [comment]
Thanks for the PR. I included some of your proposals in the [665a6b](https://github.com/jacekschae/shadow-cljs-tailwindcss/commit/665a6b84a953892064f7a4accab436cffba21056) commit. Sorry that it took me so long.
